### ISSUE TITLE
[Feature Request]: Thunar Float Dialogue Boxes

### ISSUE THREAD

**Issue by Dreded** [JaKooLit/OpenSuse-Hyprland#10]
### Description
Thunars usual floating windows should float as to not shift all the windows about

### Window Rules
windowrulev2 = float, class:([tT]hunar), title:(File Operation Progress)
windowrulev2 = float, class:([tT]hunar), title:(Confirm to replace files)

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/commit/5b97602584a1caf41439f8cfc9e6a762eec51b4c

will be pushed on next release



I invite you to contribute this dots
https://github.com/JaKooLit/Hyprland-Dots

These are dots which I used for all my distro-hyprland projects
