### ISSUE TITLE
[Bug]: Error after installing hyprland

### ISSUE THREAD

**Issue by zexy72** [JaKooLit/OpenSuse-Hyprland#11]
### Description

I did a clean install of openSUSE GNOME and then run the script. There were errors and many things were not loaded. I have never used hyprland before so I don't know.

Following are the errors:

Config error in file /home/ak/.config/hypr/UserConfigs/User Settings.conf at line 8: Invalid config line 

Config error in file /home/ak/.config/hypr/UserConfigs/User Settings.conf at line 59: cannot parse "$color2" as an int.

Gonfig error in file /home/ak/.config/hypr/hyprland.conf at line 19: Config error in file /home/ak/.config/hypr/UserConfigs/UserSettings.conf at line 8: Invalid config line 

Config error in file /home/ak/.config/hypr/UserConfigs/UserSettings.conf at line 59: cannot parse "Scolor2" as an int.

### Steps to Reproduce

1. Clean install of openSUSE GNOME.
2. Cloning the OpenSuse-Hyprland git repo
3. Making install script executable with chmod and running it.

### Expected Behavior

Hyperland should have worked with dotfiles and wallpapers.

### Actual Behavior

Black screen and the above error

### Environment

- Linux Distro: OpenSuse Tumbleweed 
- Linux Version, output of `uname -a`: 6.8.1
- Hyprland Version, output of `hyprctl version`: It shows built from branch at commit dirty ()
- Installation Environment: On Main Hardware, Asus Vivobook Laptop

**Comment by JaKooLit** [comment]
this looks like pywal was not properly loaded

inside the opensuse-hyprland folder, it creates install-logs folder

review the contents and look for errors

**Comment by Dreded** [comment]
actual issue and solution here https://github.com/JaKooLit/OpenSuse-Hyprland/issues/8#issuecomment-2021315942
