### ISSUE TITLE
qt6-svg install fail

### ISSUE THREAD

**Issue by Sharkitty** [JaKooLit/OpenSuse-Hyprland#3]
`qt6-svg` install fails systematically. I checked and there is no package with this name in OpenSUSE Tumbleweed. However there is a `qt6-svg-devel`. Perhaps is that the required package?

**Comment by JaKooLit** [comment]
interesting.... it is in here according to this

https://software.opensuse.org/package/qt6-svg


Ill check later on and will adjust accordingly

thanks

**Comment by Sharkitty** [comment]
That's weird :thinking:
Only explanation I have would be a naming change in a recent snapshot, because it happens. But why does it still appear here I don't know... Maybe it's just the time this websites reflects the naming change?

**Comment by JaKooLit** [comment]
(https://github.com/JaKooLit/OpenSuse-Hyprland/commit/fdd87cd2adf84b9bde0fc97511ea5390156c52b0)
