### ISSUE TITLE
[Bug]: After fresh install on KDE/Plasma version. YaST wont start in GUI version

### ISSUE THREAD

**Issue by MacGregor129** [JaKooLit/OpenSuse-Hyprland#31]
### Description

After using script on fresh installation of Tumbleweed with Plasma DE. YaST won't start in GUI version. After asking for password it closes with following error:
` Password: 
 Authorization required, but no authorization protocol specified
 Authorization required, but no authorization protocol specified`

### Steps to Reproduce

1. Install Tumbleweed from net install using plasma as DE
2. Reboot to fresh installation and run script
3. Reboot and login using Hyprland. Try to start YaST from app launcher

### Expected Behavior

YaST starts with working GUI

### Actual Behavior

YaST closes unexpectedly after providing password

### Additional Information

Fixed by using: `xhost +si:localuser:root`

I'm pretty new to linux so no idea if something important and don't understand full what was the issue. Just decided to mention issue I stumbled upon and managed to fix with some google searching. And sorry for blank bug report at first. Apparently hitting enter when editing title submits report...

**Comment by JaKooLit** [comment]
Thanks alot for sharing the fix.
so this fix, where should be placed?

cause I will add on the readme so they can refer to this.

ps, no worries about blank bug report. You have edited it

**Comment by MacGregor129** [comment]
As far as I understand. This command needs to be used at each sesion start. So added to startup I guess?

**Comment by vumball** [comment]
I have this issue as well. I added the polkit-kde-agent-1 to the startup script, but still no luck. I did a clean install of Tumbleweed with kde as well and then applied the hyprland script.

**Comment by JaKooLit** [comment]
anybody got any clue if this is fixed? I dont use yast so I dont know

another thing, I dont if somebody tried

but sudo -E program

should help with opening gui on root


see last part
https://wiki.archlinux.org/title/Running_GUI_applications_as_root

**Comment by JaKooLit** [comment]
https://forums.opensuse.org/t/error-when-opening-yast-applications-after-installing-patterns-opensuse-kde-yast-and-patterns-opensuse-x11-yast/173011/37?page=2

**Comment by twistedttea** [comment]
Hit this issue, and didn't want to all x server apps to root by default. Found this reddit post that fixes the issue just by installing libqt5-qtwayland and qt6-wayland. 

https://www.reddit.com/r/openSUSE/comments/16g5oq5/yast_on_sway_or_hyprland/
