### ISSUE TITLE
Changing the current keyboard layout to English.

### ISSUE THREAD

**Issue by vailrahmatulin** [JaKooLit/OpenSuse-Hyprland#32]
### Issue

When you change the wallpaper, the current keyboard layout changes to the default layout. This happens both when you automatically change the wallpaper, and when you change it by pressing the Win+w keys. The problem was noticed when the script was triggered PywalSwww.sh . I'm sorry for my English.

### Steps to Reproduce

1. Install an additional keyboard layout
2. Switch the keyboard layout
3. Run the script ./.config/hypr/scripts/PywalSwww.sh

### Expected Behavior

The keyboard layout should not change

### Actual Behavior

The keyboard layout is changing

### Environment
- Linux Distro: Archlinux
- Linux Version, output of `uname -a`: OS: Arch Linux x86_64 Kernel: 6.9.1-zen1-1-zen Shell: fish 3.7.1 Resolution: 2560x1440 DE: Hyprland WM: sway Theme: Adwaita [GTK2], Tokyonight-Light-B-LB [GTK3] Icons: Adwaita [GTK2], Tokyonight-Light [GTK3] Terminal: kitty CPU: 11th Gen Intel i7-11800H (16) @ 4.600GHz  GPU: Intel TigerLake-H GT1 [UHD Graphics] GPU: NVIDIA GeForce RTX 3070 Mobile / Max-Q Memory: 4782MiB / 64004MiB 
- Hyprland Version, output of `hyprctl version`: 
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

- Installation Environment: On The Main Hardware

**Comment by JaKooLit** [comment]
I dont think its the pywalswww causing it but the autorefresh of hyprland

the refresh.sh and anything associated to changing wallpaper is for it to take effect on waybar, rofi, etc etc

if you want the NOT to refresh after changing wallpapers, you should disable all the scripts at the bottom of WallpaperSelect.sh and any other wallpaper related scripts



I suggest that the keyboard layout you put on the UserSettings.conf is your main keyboard layout

**Comment by vailrahmatulin** [comment]
No, a separate launch **Refresh.sh** does not lead to a change of layout, but the launch **PywalSwww.sh** switches the layout, which is strange, since there is nothing in this script that could do this. Moreover, just the command `wal -i $HOME/.config/rofi/.current_wallpaper -s -t -n -e &` also changes the layout.

**Comment by JaKooLit** [comment]
no im not talking about the refresh.sh

hyprland have a built in auto refresh so any changes to settings, it will take effect immediately..

so by changing the color with pywal, the colors also change, and hyprland will try to use that...

you can try to test it..

say for example change a border size or gaps or anything you want to change on hyprland settings

**Comment by vailrahmatulin** [comment]
`hyprctl keyword general:gaps_out 20` does not change the keyboard layout

**Comment by JaKooLit** [comment]
> hyprctl keyword general:gaps_out 20

try changing the actual file instead

**Comment by JaKooLit** [comment]
like I said try to put your main kb_layout first

ie

kb_layout=ru,us

**Comment by vailrahmatulin** [comment]
The problem is that I don't need to change the layout to the default one. It is necessary that the layout does not change at all. since I constantly switch from one layout to another while working, and if it changes to Russian instead of English, it will not improve the situation.

**Comment by vailrahmatulin** [comment]
I have commented out all the lines referring to PywalSwww.sh . It worked for me. But unfortunately, this is not the solution to the problem.

**Comment by JaKooLit** [comment]
https://wiki.hyprland.org/Configuring/Variables/#misc

you might want to change the auto-reload feature of Hyprland

However, just as a test, I have added other kb layouts to my system through the settings and I did other changes .. any changes including wallpaper switch, the last kb_layout set still keeps it there...

BUT, obviously, my keyboard output didnt changed since it was not properly set up...

Try to check setting of your Ibus (assume you use of course). Could be there the default settings? Im just guessing here

**Comment by JaKooLit** [comment]
Your last option is to approach hyprland team.. dotfiles 

the pywal.sh is just to refresh the colors as per your set wallpaper.

if you are curious about the letters after wal

here is the link
https://github.com/dylanaraps/pywal/wiki/Getting-Started#how-to-use-wal

**Comment by vailrahmatulin** [comment]
Thanks, I'll try, the topic can be closed.
