### ISSUE TITLE
The keyboard layout widget does not respond to the layout change.

### ISSUE THREAD

**Issue by vailrahmatulin** [JaKooLit/OpenSuse-Hyprland#33]
### Description

When you press the key combination responsible for changing the keyboard layout (for example, alt+shift), the corresponding Waybar widget does not respond to the change of layout and continues to show the previous layout. When you click on the widget, the animation of the layout change occurs, a message appears about the layout change, but the keyboard layout remains the same. In fact, the widget is useless, it does not show the current layout and does not change it. Forgive me for my English.

### Steps to Reproduce

1. Install an additional keyboard layout
2. Switch the keyboard layout 

### Expected Behavior

The widget must react

### Actual Behavior

The widget is not responding

### Environment

Linux Distro: Archlinux

Linux Version, output of uname -a: OS: Arch Linux x86_64 Kernel: 6.9.1-zen1-1-zen Shell: fish 3.7.1 Resolution: 2560x1440 DE: Hyprland WM: sway Theme: Adwaita [GTK2], Tokyonight-Light-B-LB [GTK3] Icons: Adwaita [GTK2], Tokyonight-Light [GTK3] Terminal: kitty CPU: 11th Gen Intel i7-11800H (16) @ 4.600GHz GPU: Intel TigerLake-H GT1 [UHD Graphics] GPU: NVIDIA GeForce RTX 3070 Mobile / Max-Q Memory: 4782MiB / 64004MiB

Hyprland Version, output of hyprctl version:
Hyprland, built from branch at commit cba1ade848feac44b2eda677503900639581c3f4 (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

Installation Environment: On The Main Hardware

**Comment by JaKooLit** [comment]
how long did you wait for it to change? It wont change right away if I remember it correctly..

**Comment by JaKooLit** [comment]
Plus, sorry since I dont use any other layout and this was just added / tweaked by some users before

**Comment by vailrahmatulin** [comment]
I figured out what the problem was. The fact is that in your SwitchKeyboardLayout script.sh is used by at-translated-set-2-keyboard. This is not a universal solution when connecting multiple keyboards. Accordingly, your script Processes several layouts, but only for one keyboard. In my case, it's a laptop keyboard. The script does not work on an external USB keyboard. When I clicked on the widget, the layout on the laptop keyboard changed, and I continued to type on the external one. I fixed the script SwitchKeyboardLayout.sh now it changes the layout on all connected keyboards.

```
#!/bin/bash
# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  ##
# This is for changing kb_layouts. Set kb_layouts in $settings_file

layout_f="$HOME/.cache/kb_layout"
settings_file="$HOME/.config/hypr/UserConfigs/UserSettings.conf"
notif="$HOME/.config/swaync/images/bell.png"

# Check if ~/.cache/kb_layout exists and create it with a default layout from Settings.conf if not found
if [ ! -f "$layout_f" ]; then
  default_layout=$(grep 'kb_layout=' "$settings_file" | cut -d '=' -f 2 | cut -d ',' -f 1 2>/dev/null)
  if [ -z "$default_layout" ]; then
    default_layout="us" # Default to 'us' layout if Settings.conf or 'kb_layout' is not found
  fi
  echo "$default_layout" > "$layout_f"
fi

current_layout=$(cat "$layout_f")

# Read keyboard layout settings from Settings.conf
if [ -f "$settings_file" ]; then
  kb_layout_line=$(grep 'kb_layout=' "$settings_file" | cut -d '=' -f 2)
  IFS=',' read -ra layout_mapping <<< "$kb_layout_line"
fi

layout_count=${#layout_mapping[@]}

# Find the index of the current layout in the mapping
for ((i = 0; i < layout_count; i++)); do
  if [ "$current_layout" == "${layout_mapping[i]}" ]; then
    current_index=$i
    break
  fi
done

# Calculate the index of the next layout
next_index=$(( (current_index + 1) % layout_count ))
new_layout="${layout_mapping[next_index]}"

# Update the keyboard layout
hyprctl switchxkblayout "at-translated-set-2-keyboard" "$new_layout"
echo "$new_layout" > "$layout_f"

# Notification for the new keyboard layout
#notify-send -u low -i "$notif" "new KB_Layout: $new_layout"


# Created by T-Crypt

get_keyboard_names() {
    hyprctl devices -j | jq -r '.keyboards[].name'
}

change_layout() {
    local got_error=false

    while read -r name; do
        hyprctl switchxkblayout "$name" next
        if [[ $? -eq 0 ]]; then
            echo "Switched the layout for $name."
        else
            >&2 echo "Error while switching the layout for $name."
            got_error=true
        fi
    done <<< "$(get_keyboard_names)"

    if [ "$got_error" = true ]; then
        >&2 echo "Some errors were found during the process..."
        return 1
    fi

    return 0 # All layouts had been cycled successfully
}

if ! change_layout; then
    notify-send -u low -t 2000 'Keyboard layout' 'Error: Layout change failed'
    >&2 echo "Layout change failed."
    exit 1
else
    #notify-send -u low -t 2000 'Keyboard layout' 'Current Layout Changed'
	notify-send -u low -i "$notif" "new KB_Layout: $new_layout"
    #echo "Layout change successful."
fi
```
I took the second part of the script from here: [T-Crypt](https://github.com/T-Crypt/hyprland-layoutswitch
)
For the widget to work correctly, it is necessary in the UserSettings.conf file in the input section of the 
```
 kb_variant=
 kb_model=
 kb_options=
 kb_rules=
```
 leave empty
And insert a line 
`bindn = ALT_L, SHIFT_L, exec, $scriptsDir/SwitchKeyboardLayout.sh `
in the file UserKeybinds.conf 
After that, the script will be called when you press Alt+Shift. Note that the `bindn` command is used, this is not a typo, as far as I understand, this is done so that application menus are not called, for example in Firefox.

Sorry again for my English. If something is difficult to understand, do not hesitate to ask, I will try to help.

**Comment by JaKooLit** [comment]
cool thanks for sharing

if you want you can make a PR here

https://github.com/JaKooLit/Hyprland-Dots/tree/development

so you will be credited as well
