### ISSUE TITLE
[Bug]: Cant Login to either XFCE or Hyprland after running the install script

### ISSUE THREAD

**Issue by Philiam94** [JaKooLit/OpenSuse-Hyprland#34]
Hello everyone,

I ran the ./install.sh on OpenSuse Tumbleweed. So now after the installation completed I cannot log into either xfce (which I used before) or Hyprland. I can use tty to login in and manually start Hyprland, but just from basic actions the system gets stuck and I have to forcefully restart the system. In the log in screens it however just shows me "Login failed" when I type my username and password. If I choose XFCE I can atleast login is as root.

I dont really know where to start looking for problems. So I am open for any ideas.

Please note that I am gone for the weekend, so I will only be able to reply or answer to questions starting next week.

Thanks in advance for your help.

**Comment by JaKooLit** [comment]
what is your login manager?

**Comment by Philiam94** [comment]
I used sddm and manually installed the sddm-qt6 while removing the normal sddm that was installed before. After doing so stuff got faster but didnt do anything else.

**Comment by JaKooLit** [comment]
seems like the sddm-qt6 is not able to look for the xsessions.

I suggest to reinstall the normal sddm

and then once xfce is fixed, rerun hyprland installer again. That time dont choose to install sddm from the script

mighy be some packages were not properly installes by the script. You can verify the logs inside Opensuse-Hyprland/Install-Logs

**Comment by Philiam94** [comment]
I will do so next time I have the time. Thank you already. Maybe leave this issue open until next week since I am gone for the weekend.

**Comment by JaKooLit** [comment]
Hi... so I thought I have switched over to sddm-qt6 theme. It turns out I didnt :)

https://github.com/JaKooLit/OpenSuse-Hyprland/commit/ec53fa79053f3811021f1492eb698ea474108dc8

Anyway, I have corrected now for qt6 type of sddm theme...

And btw, I have just updated and released a new dots..

So I suggest to delete and re-download a fresh OpenSuse-Hyprland script and re-run

so you will get the whole shebang :)
