### ISSUE TITLE
[Bug]: qt6-qt5compat doesn't install --> SDDM error

### ISSUE THREAD

**Issue by adriabrucortes** [JaKooLit/OpenSuse-Hyprland#39]
### Description

The qt6-qt5compat package doesn't install, so SDDM shows an error.

### Steps to Reproduce

1. Make a clean server installation
2. Run the script
3. Reboot

### Expected Behavior

I expected to see the custom SDDM theme. 

### Actual Behavior

Was faced with the vanilla design and a red message that says:
"qt6-qt5compat not installed".

I looked at the SDDM script's log and there was an error saying qt6-qt5compat hadn't been installed. I tried installing it myself but it says it's not found in the repositories.

### Environment

- Linux Distro: OpenSuse TW
- Installation Environment: Bare metal (i9-9900KF & RTX 2080 Ti)
- Other info: 3440x1440

**Comment by JaKooLit** [comment]
what about installing

qt6-qt5compat-devel

sudo zypper in qt6-qt5compat-devel

let me know if it fixed so I can change the script..

atm, im not at home and travelling so I cannot test it.

thanks

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/OpenSuse-Hyprland/commit/dd354e4af6890facb65be746c18269bfb841199d

found issue.. it needs qt6-qt5compat-imports instead of devel
