### ISSUE TITLE
Does not launch on current Tumbleweed.

### ISSUE THREAD

**Issue by kpmgeek** [JaKooLit/OpenSuse-Hyprland#4]
On a 11th gen Intel based laptop with the iGPU, installed immediately after a server role install of Tumbleweed, I'm unable to get this to launch. Hyprland shows a cursor on a black screen for about half a second before throwing back to sddm and launching from the console doesn't show anything meaningful suggesting an error.

**Comment by JaKooLit** [comment]
kindly send me the install logs as without it, I cannot say anything.

if you installed on a VM or any virtual, make sure to enable 3d acceleration

**Comment by kpmgeek** [comment]
This was on bare-metal, but I have reproduced it on a VM with 3d accel enabled.  Where does the installer generate logs?

**Comment by JaKooLit** [comment]
its on the OpenSuse-Hyprland folder

**Comment by kpmgeek** [comment]
[logs.tar.gz](https://github.com/JaKooLit/OpenSuse-Hyprland/files/13799880/logs.tar.gz) This is from the vm install, not the baremetal.

**Comment by JaKooLit** [comment]
thanks for providing the log...

I dont see anything unusual but only generation of initramfs which says lots of modules not found.. although Im not entirely sure it is relevant

can you re-ran this

sudo zypper dup --from packman --allow-vendor-change

and also, when you were prompted for keyboard language, which layout you entered?

Mind you that entering a wrong layout, hyprland wont start.

You can edit it in

~/.config/hypr/UserConfigs/UserSettings.conf

Look for

input {
  kb_layout=
  
  If you put a different layout, trying changing to us first

i.e.  
  input {
  kb_layout=us
  
  and thenlogout and relog in or reboot
  
  let me know

**Comment by kpmgeek** [comment]
![image](https://github.com/JaKooLit/OpenSuse-Hyprland/assets/19271687/ef0c806e-faed-415a-b516-54613a886f27)
Not sure which did it, but between that and manually setting my layout to us on the vm (I remember noticing it went undetected and blank on the vm, but it definitely autodetected us on baremetal)

**Comment by JaKooLit** [comment]
so we can close this issue?

**Comment by kpmgeek** [comment]
I mean, I'm going to try in a bit on a clean install of the server to see if it's still missing packages that make it fail to start

**Comment by kpmgeek** [comment]
On a clean install of the server installation profile on bare metal it worked, where the only thing I ran into way rofi-wayland failing to nstall due to suse's cdn timing out, which was easily rectified. It must have been an issue related to the keymap. You can close it.
