### ISSUE TITLE
[Bug]: PC crashes after launching Thunar

### ISSUE THREAD

**Issue by adriabrucortes** [JaKooLit/OpenSuse-Hyprland#40]
### Description

Thunar crashes upon launching it.

### Steps to Reproduce

1. Make a clean server installation
2. Run the script
3. Reboot

### Expected Behavior

I expected to use Thunar normally.

### Actual Behavior

Whenever I launch Thunar (installed with the script), my PC crashes completely. I have to force reboot.

### Environment

- Linux Distro: OpenSuse TW
- Installation Environment: Bare metal (i9-9900KF & RTX 2080 Ti)
- Other info: 3440x1440

**Comment by JaKooLit** [comment]
can you provide the .....thunar.log inside the Install-Logs directory in OpenSuse-Hyprland?

**Comment by JaKooLit** [comment]
closing as no response
