### ISSUE TITLE
[Bug]: nvidia-drivers-G06 doesn't exist in the tumbleweed/leap repo

### ISSUE THREAD

**Issue by adriabrucortes** [JaKooLit/OpenSuse-Hyprland#41]
This is just an fyi:

"nvidia-drivers-G06" doesn't exist in the tumbleweed/leap repo. It's supposed to just be "nvidia-video-G06".
From the wiki:

![image](https://github.com/JaKooLit/OpenSuse-Hyprland/assets/79582880/eced2cb1-c41d-4507-a34e-e4f48df7a496)

**Comment by adriabrucortes** [comment]
The same goes for "openSUSE-repos-NVIDIA" btw

**Comment by JaKooLit** [comment]
thanks for this... Ill clean up the install script next week.. Just checked now and seems like procedure have changed.

there is also now a automatic nvidia installer which I will change into that one instead..

thanks for the heads up

**Comment by JaKooLit** [comment]
Ill keep this open as a reminder for me

**Comment by JaKooLit** [comment]
![swappy-20240531-024904](https://github.com/JaKooLit/OpenSuse-Hyprland/assets/85185940/45a5b574-c0e5-4430-b1c7-cc86e74b963a)


well it does exist
