### ISSUE TITLE
[Bug]: npm21 not found

### ISSUE THREAD

**Issue by scrapes** [JaKooLit/OpenSuse-Hyprland#49]
`[ERROR] npm21 failed to install :( , please check the install.log. You may need to install manually! Sorry I have tried :(`

npm21 on OpenSuse Tumbleweed ARM not found.
I suspect it was replaced with npm22, since npm21 isnt found anymore in the repos online.

I will try to look into it further

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/OpenSuse-Hyprland/commit/9458d2cde6c5dc49951ff37aebefd915c1a665a3
