### ISSUE TITLE
[Feature Request]: Waybar hide/unhide

### ISSUE THREAD

**Issue by JJsdxd** [JaKooLit/OpenSuse-Hyprland#54]
### Description

The current shortcut super +B doesn't unhide the bar since Waybar got updated I believe.

### Use Case

To hide and unhide the bar at the top so user can have more effective screenspace for apps.

### Proposed Solution

I think it is just an update issue since I saw people complain about it in Waybar repo  issue #3477

**Comment by JJsdxd** [comment]
Found a workaround 
You can reload the config to get bar back
As hiding still works

**Comment by JaKooLit** [comment]
This has been fixed by waybar updates
