### ISSUE TITLE
[Feature Request]: PRIME render offload doesnt work out of the box

### ISSUE THREAD

**Issue by D4vidGarcia** [JaKooLit/OpenSuse-Hyprland#6]
### Description

A easy way to offload or select a GPU for a specific task using PRIME.

### Use Case

This could save a lot of energy on laptops with nvidia GPUs. As right now if you have one and use this script, selecting nvidia drivers at installation, your laptop or desktop will only use the dedicated gpu for all the tasks, which is really inefficient.

### Proposed Solution

PRIME or PRIME SUSE out of the box, with a hotkey to change completely between GPUs and some tool to easily add applications that offload to the dGPU.

### Alternatives

Installing everything manually (which hasn't worked for me).

**Comment by JaKooLit** [comment]
take note, this is not a universal solution to laptops. ROG for example, the suse-prime is interfering with supergfxctl



Thats the reason why I dont want to implement it as it is not a universal functioning app
