### ISSUE TITLE
oh-my-zsh

### ISSUE THREAD

**Issue by skarpinis** [JaKooLit/OpenSuse-Hyprland#60]
### Description

when source .zshrc get errors
/home/sk/.oh-my-zsh/oh-my-zsh.sh:99: parse error near `done'
/proc/self/fd/12:33: parse error near `done'

### Steps to Reproduce

1. source .zshrc

### Expected Behavior

no errors

### Actual Behavior

few errors mentioned above

**Comment by JaKooLit** [comment]
need more info

just newly installed?

update? or what?

**Comment by skarpinis** [comment]
Installed few days ego, just added few alias.

**Comment by skarpinis** [comment]
fixed was bad alias like fi="flatpak install" most likely conflict happen :)
