### ISSUE TITLE
[Bug]: keyboard shortcut

### ISSUE THREAD

**Issue by bobblkabb** [JaKooLit/OpenSuse-Hyprland#7]
### Description
Can't assign ALT+SHIFT+Q to do 'killactive'.
Changed $mainMod from SUPER to ALT (-> 'bind = $mainMod SHIFT, Q, killactive') and commented the 'closewindow' line, which was already assigned to $mainMod+SHIFT+Q.

**Comment by JaKooLit** [comment]
I dont understand what you intend to do....

**Comment by bobblkabb** [comment]
Remap SUPER+Q to ALT+SHIFT+Q.

**Comment by bobblkabb** [comment]
```
$mainMod = ALT
bind = $mainMod SHIFT, Q, killactive,
```

**Comment by bobblkabb** [comment]
Seems there's a problem with SHIFT. There are more commands I can't execute

**Comment by bobblkabb** [comment]
`kb_options = grp:alt_shift_toggle `
was the problem
