### ISSUE TITLE
[Bug]: Short description of the issue

Used it on a fresh server install and it's not working

### ISSUE THREAD

**Issue by Rick-1242** [JaKooLit/OpenSuse-Hyprland#8]
### Description

I installed openSuse Tumbleweed (dual boot) with a server install and every worked just fine, I used the script and got to the end, reboot and the trackpad/pointer doesn't work in the SDDM login interface. I logged in and I got these error messages.
![20240322_003034.jpg](https://github.com/JaKooLit/OpenSuse-Hyprland/assets/71984096/19ebdf2f-9dba-43d0-868b-d2601db5d56c)

What did I do wrong? How can I fix this?

During installation I got this error, maybe it's causing it![20240322_002601.jpg](https://github.com/JaKooLit/OpenSuse-Hyprland/assets/71984096/7d7a89c9-d7dc-49fa-bdc7-6561f257b400)

e.g.,

- Linux Distro: [OpenSuse TW]
- Installation Environment: Asus G14 laptop, I also installed the ROG tools
- Other info: AMD graphics card

**Comment by Dreded** [comment]
this is an issue with pywal and the newest ImageMagick-7 default policy that doesnt allow writing to stdout

i detailed the issue here: https://github.com/dylanaraps/pywal/issues/729#issue-2209060629 with a solution

**Comment by zexy72** [comment]
Used the solution, generated the files with the command at top, reboot, error gone, problem solved. Thanks.

**Comment by zexy72** [comment]
Wallpaper reloading was not working,
Error : GTK2 requires python 2
Python 2 was missing

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/OpenSuse-Hyprland/commit/e0d11f0724d56f78c623cdee1be0c24558a13de6

Have dropped pywal and moved to wallust
