### ISSUE TITLE
[Bug]: NVIDIA XWayland lockup and pywal

### ISSUE THREAD

**Issue by Dreded** [JaKooLit/OpenSuse-Hyprland#9]
### Issue
on my nvidia card anything that uses Xwayland freezes, this means that using pywal to set the wallpaper causes a lockup

### Solution
since it seems pywal isn't used to set the wallpaper, just to get its colors we can disable it from setting the wallpaper  with the -n and -e options. as far as I can tell this makes everything work as expected and avoids calling xwayland

edit `.config/hypr/scripts/PywalSwww.sh`
* change -> `wal -i "$wallpaper_path" -s -t &`
* to -> `wal -i "$wallpaper_path" -s -t -n -e &`

#### edit  `.config/hypr/initial-boot.sh`
* change -> `wal -i "$wallpaper_path" -s -t &`
* to -> `wal -i "$wallpaper_path" -s -t -n -e &`

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/commit/f019c0f15946484e656acbf78943f672b20f96d4

will be push on the next dots release
